version: '2'
services:  
  sqllinux:
    build: .         
    container_name: SqlServerLinux
    volumes:
      - .\Sqlserver\dados:/var/opt/mssql
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Senha@2016