version: '2'
services:  
  sqllinux:
    image: marcosflavio/sqlserver
    container_name: sqlserver_linux
    volumes:
      - D:\Docker_Sqlserver\dados1:/var/opt/mssql
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bolinha@2016